### ISSUE TITLE
Cannot install with device_info_plus v10

### ISSUE THREAD

**Issue by lukas-pierce** [Boehrsi/device_marketing_names#13]
Please fix dependencies, not I need downgrade to device_info_plus v9.1.2

<img width="1701" alt="Screenshot device_marketing_names" src="https://github.com/Boehrsi/device_marketing_names/assets/4938316/015ea871-6d6d-4697-a8d5-beced3aad528">

**Comment by Boehrsi** [comment]
Thanks for bringing this up. The code was already adjusted a few days ago and a new version, containing the fix will be released today (28.03.2024).

**Comment by Boehrsi** [comment]
Version 0.8.2 was released just now and pub.dev is updating. As soon as pub.dev is done with indexing and checking the new version it should be available. 

Closing this issue as fixed.

**Comment by lukas-pierce** [comment]
@Boehrsi Thank you
