### ISSUE TITLE
Update device_info_plus dependency to the latest

### ISSUE THREAD

**Issue by volkangurol** [Boehrsi/device_marketing_names#3]
**Is your feature request related to a problem? Please describe.**
Using latest version dependency device_info_plus (^6.0.0)  gives version solving failed. 
Thank you.

**Comment by Boehrsi** [comment]
Thanks for creating this issue. I will merge https://github.com/Boehrsi/device_marketing_names/pull/2 soon and will publish a new version. This should fix the problem.

**Comment by Boehrsi** [comment]
Fixed via: https://github.com/Boehrsi/device_marketing_names/pull/2
Release information: https://github.com/Boehrsi/device_marketing_names/releases/tag/0.5.0
Pub.dev release: https://pub.dev/packages/device_marketing_names
